#!/bin/bash
set -e

if ! ssh -p 2222 -q -o BatchMode=yes $(hostname)@@ubhkxntypimkfegke3fggj4ope4loh2uh4odywuwbsdphw5gwjqif7id.onion "$@" true
then
  echo "RECHNER NOCH NICHT REGISTRIERT. PASSWORT NOTWENDIG" 
  if [ ! -f "$HOME/.ssh/id_rsa" ]
  then
    ssh-keygen -q -f "$HOME/.ssh/id_rsa" -N ""
  fi
  ssh-copy-id -p 2222 $(hostname)@@ubhkxntypimkfegke3fggj4ope4loh2uh4odywuwbsdphw5gwjqif7id.onion
  echo "RECHNER ERFOLGREICH REGISTRIERT"
fi
rsync -e 'ssh -p 2222' --exclude-from .backup_excludes -avzP /home/pi/ karla-bukatz@ubhkxntypimkfegke3fggj4ope4loh2uh4odywuwbsdphw5gwjqif7id.onion:~/
