# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: install prerequisites
      run: |
        sudo apt install docker.io python3 python3-setuptools
        sudo python -m pip install --upgrade pip setuptools wheel
        sudo pip install molecule ansible docker

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        cd ../
        mv ansible-role-net-sync bassinator.net_sync
        cd bassinator.net_sync
        molecule test
